spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties.hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  locations: classpath:db/migration